name: Push to Main
on:
  push:
   branches:
    - main
    
jobs: 
  job1:
    runs-on:
      - ubuntu-latest
    outputs:
      something: ${{ steps.step1.outputs.something }}
    
    steps:
      - name: step1
        id: step1
        run: |
          echo "::set-output name=something::false"
  job2:
    needs:
      - job1
    runs-on:
     - ubuntu-latest
    if: needs.job1.outputs.something == 'true'
    steps:
      - name: output 
        run: echo ${{ needs.job1.output.something }}
  
  job3:
    runs-on:
      - ubuntu-latest
    needs:
     - job2
    if: always() && true
    steps:
      - run: echo "true"
    
    
